// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkEtTwvnJNUmkpxlnUWXrWZv8-D0JLUaw',
    appId: '1:752393826054:web:e2b807005237e0c878b887',
    messagingSenderId: '752393826054',
    projectId: 'insta-bdf99',
    authDomain: 'insta-bdf99.firebaseapp.com',
    storageBucket: 'insta-bdf99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMUJW5QNkshaUxEqImkjVVEJUxZPKrO20',
    appId: '1:752393826054:android:4367c895501fdd9d78b887',
    messagingSenderId: '752393826054',
    projectId: 'insta-bdf99',
    storageBucket: 'insta-bdf99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHHF6kkZreKIQN_Hup3lUMZm7m55c4Qw',
    appId: '1:752393826054:ios:61d305066fdbde6a78b887',
    messagingSenderId: '752393826054',
    projectId: 'insta-bdf99',
    storageBucket: 'insta-bdf99.firebasestorage.app',
    iosBundleId: 'com.example.insta',
  );
}
